### ISSUE TITLE
Error : BrowserAuthError: pkce_not_created

### ISSUE THREAD

**Issue by saravanac** [Azure-Samples/ms-identity-javascript-react-tutorial#328]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [x ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> I followed the instructions as per the scenario 3-1 - https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api
> React App and API is running on Ubuntu server
> I am trying to call the React app remotely via browser
> When I get to step Explore the sample I get below error

> BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')
>     at BrowserAuthError.AuthError [as constructor] (AuthError.ts:49:1)
>     at new BrowserAuthError (BrowserAuthError.ts:195:1)
>     at BrowserAuthError.createPkceNotGeneratedError (BrowserAuthError.ts:207:1)
>     at PkceGenerator.<anonymous> (PkceGenerator.ts:67:1)
>     at step (claimUtils.js:206:1)
>     at Object.throw (claimUtils.js:206:1)
>     at rejected (claimUtils.js:206:1)

### Any log messages given by the failure
BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')
    at BrowserAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new BrowserAuthError (BrowserAuthError.ts:195:1)
    at BrowserAuthError.createPkceNotGeneratedError (BrowserAuthError.ts:207:1)
    at PkceGenerator.<anonymous> (PkceGenerator.ts:67:1)
    at step (claimUtils.js:206:1)
    at Object.throw (claimUtils.js:206:1)
    at rejected (claimUtils.js:206:1)
>

### Expected/desired behavior
I expect to be signed in and see the Todo List page:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/7839136/5df68900-98cc-4622-b564-475ed3d91b59)

>

### Library version

>

### Browser and version

> Chrome 115.0.5790.110 (Official Build) (64-bit)

### Mention any other details that might be useful
React app and API is running on Linux Ubuntu server
I am trying to access launch page remotely via Chrome browser
I have configured following redirect URIs:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/7839136/6bd484c7-5aaa-4cfa-9df6-49273108d623)

>

Thanks! We'll be in touch soon.

**Comment by saravanac** [comment]
How do I enable HTTPS to try this out remotely?

**Comment by saravanac** [comment]
Fixed using HTTPS=true npm start
